export { default as About } from './About';
export { default as Cards } from './Cards';
export { default as Eyes } from './Eyes';
export { default as Featured } from './Featured';
export { default as Footer } from './Footer';
export { default as Landing } from './Landing';
export { default as Marquee } from './Marquee';
export { default as Menu } from './Menu';
export { default as Navbar } from './Navbar';
